ALTER TABLE schema_migrations COMMENT = '数据库迁移记录表',
  MODIFY COLUMN version VARCHAR(32) NOT NULL COMMENT '迁移版本号',
  MODIFY COLUMN name VARCHAR(255) NOT NULL COMMENT '迁移文件名',
  MODIFY COLUMN checksum CHAR(64) NOT NULL COMMENT '迁移文件校验值',
  MODIFY COLUMN applied_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '迁移应用时间';

ALTER TABLE users COMMENT = '系统用户表',
  MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '用户ID',
  MODIFY COLUMN username VARCHAR(64) NOT NULL COMMENT '登录账号',
  MODIFY COLUMN password_hash CHAR(64) NOT NULL COMMENT '密码哈希',
  MODIFY COLUMN display_name VARCHAR(128) NOT NULL COMMENT '显示名称',
  MODIFY COLUMN role ENUM('admin', 'user') NOT NULL DEFAULT 'user' COMMENT '系统角色',
  MODIFY COLUMN status ENUM('active', 'disabled') NOT NULL DEFAULT 'active' COMMENT '用户状态',
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE shops COMMENT = '店铺信息表',
  MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '店铺ID',
  MODIFY COLUMN shop_name VARCHAR(128) NOT NULL COMMENT '店铺名称',
  MODIFY COLUMN platform VARCHAR(32) NOT NULL DEFAULT 'temu' COMMENT '所属平台',
  MODIFY COLUMN external_code VARCHAR(128) NULL COMMENT '平台店铺编号',
  MODIFY COLUMN eu_representative VARCHAR(255) NOT NULL DEFAULT '' COMMENT '欧代信息',
  MODIFY COLUMN shop_url VARCHAR(1000) NOT NULL DEFAULT '' COMMENT '店铺URL',
  MODIFY COLUMN status ENUM('active', 'paused', 'closed') NOT NULL DEFAULT 'active' COMMENT '店铺状态',
  MODIFY COLUMN created_by BIGINT UNSIGNED NULL COMMENT '创建人用户ID',
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE user_shops COMMENT = '用户店铺绑定表',
  MODIFY COLUMN user_id BIGINT UNSIGNED NOT NULL COMMENT '用户ID',
  MODIFY COLUMN shop_id BIGINT UNSIGNED NOT NULL COMMENT '店铺ID',
  MODIFY COLUMN shop_role ENUM('owner', 'operator', 'viewer') NOT NULL DEFAULT 'operator' COMMENT '用户在店铺中的角色',
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '绑定时间';

ALTER TABLE permissions COMMENT = '权限定义表',
  MODIFY COLUMN code VARCHAR(80) NOT NULL COMMENT '权限编码',
  MODIFY COLUMN name VARCHAR(128) NOT NULL COMMENT '权限名称',
  MODIFY COLUMN category VARCHAR(64) NOT NULL COMMENT '权限分类',
  MODIFY COLUMN description VARCHAR(255) NOT NULL DEFAULT '' COMMENT '权限说明',
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

ALTER TABLE role_permissions COMMENT = '角色权限绑定表',
  MODIFY COLUMN role ENUM('admin', 'user') NOT NULL COMMENT '系统角色',
  MODIFY COLUMN permission_code VARCHAR(80) NOT NULL COMMENT '权限编码',
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '授权时间';

ALTER TABLE tool_modules COMMENT = '工具中心模块表',
  MODIFY COLUMN id VARCHAR(64) NOT NULL COMMENT '工具模块ID',
  MODIFY COLUMN name VARCHAR(128) NOT NULL COMMENT '工具名称',
  MODIFY COLUMN description VARCHAR(255) NOT NULL DEFAULT '' COMMENT '工具说明',
  MODIFY COLUMN status ENUM('planning', 'active', 'paused') NOT NULL DEFAULT 'planning' COMMENT '工具状态',
  MODIFY COLUMN sort_order INT NOT NULL DEFAULT 100 COMMENT '排序值',
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE system_settings COMMENT = '系统设置表',
  MODIFY COLUMN setting_key VARCHAR(80) NOT NULL COMMENT '设置键',
  MODIFY COLUMN setting_value VARCHAR(500) NOT NULL DEFAULT '' COMMENT '设置值',
  MODIFY COLUMN description VARCHAR(255) NOT NULL DEFAULT '' COMMENT '设置说明',
  MODIFY COLUMN updated_by BIGINT UNSIGNED NULL COMMENT '更新人用户ID',
  MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE delivery_extract_batches COMMENT = '发货JSON提取批次表',
  MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '提取批次ID',
  MODIFY COLUMN source_file VARCHAR(255) NOT NULL DEFAULT '' COMMENT '来源文件或来源名称',
  MODIFY COLUMN batch_date VARCHAR(16) NOT NULL DEFAULT '' COMMENT '批次日期',
  MODIFY COLUMN source_total INT NOT NULL DEFAULT 0 COMMENT '源记录数量',
  MODIFY COLUMN extracted_total INT NOT NULL DEFAULT 0 COMMENT '提取结果数量',
  MODIFY COLUMN target_json LONGTEXT NOT NULL COMMENT '提取后的目标JSON',
  MODIFY COLUMN created_by BIGINT UNSIGNED NULL COMMENT '创建人用户ID',
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

ALTER TABLE delivery_extract_rows COMMENT = '发货JSON提取明细表',
  MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '提取明细ID',
  MODIFY COLUMN batch_id BIGINT UNSIGNED NOT NULL COMMENT '提取批次ID',
  MODIFY COLUMN supplier_id VARCHAR(64) NOT NULL DEFAULT '' COMMENT '供应商或店铺编号',
  MODIFY COLUMN shop_id BIGINT UNSIGNED NULL COMMENT '关联店铺ID',
  MODIFY COLUMN product_name TEXT NOT NULL COMMENT '商品名称',
  MODIFY COLUMN product_skc_picture VARCHAR(1000) NOT NULL DEFAULT '' COMMENT '产品图片地址',
  MODIFY COLUMN delivery_order_sn VARCHAR(64) NOT NULL DEFAULT '' COMMENT '发货单号',
  MODIFY COLUMN skc VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'SKC码',
  MODIFY COLUMN skc_num INT NOT NULL DEFAULT 0 COMMENT 'SKC数量',
  MODIFY COLUMN sku VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'SKU码',
  MODIFY COLUMN sku_num INT NOT NULL DEFAULT 0 COMMENT 'SKU数量',
  MODIFY COLUMN receiver_name VARCHAR(255) NOT NULL DEFAULT '' COMMENT '收货仓库',
  MODIFY COLUMN row_json LONGTEXT NOT NULL COMMENT '原始明细JSON',
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
