CREATE TABLE IF NOT EXISTS sales_overall_batches (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '销售总览快照ID',
  source_name VARCHAR(255) NOT NULL DEFAULT '' COMMENT '来源名称',
  supplier_id VARCHAR(64) NOT NULL DEFAULT '' COMMENT '店铺编码',
  supplier_name VARCHAR(128) NOT NULL DEFAULT '' COMMENT '店铺名称',
  source_total INT NOT NULL DEFAULT 0 COMMENT '源商品数量',
  imported_total INT NOT NULL DEFAULT 0 COMMENT '导入SKU明细数量',
  created_by BIGINT UNSIGNED NULL COMMENT '导入人用户ID',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '导入时间',
  PRIMARY KEY (id),
  KEY idx_sales_overall_batches_supplier_id (supplier_id),
  KEY idx_sales_overall_batches_created_at (created_at),
  CONSTRAINT fk_sales_overall_batches_created_by FOREIGN KEY (created_by) REFERENCES users(id)
    ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='销售总览快照批次表';

CREATE TABLE IF NOT EXISTS sales_overall_rows (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '销售总览明细ID',
  batch_id BIGINT UNSIGNED NOT NULL COMMENT '销售总览快照ID',
  supplier_id VARCHAR(64) NOT NULL DEFAULT '' COMMENT '店铺编码',
  supplier_name VARCHAR(128) NOT NULL DEFAULT '' COMMENT '店铺名称',
  product_skc_id VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'SKC码',
  product_sku_id VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'SKU码',
  product_name VARCHAR(500) NOT NULL DEFAULT '' COMMENT '商品名称',
  product_image VARCHAR(1000) NOT NULL DEFAULT '' COMMENT '商品图片',
  category VARCHAR(128) NOT NULL DEFAULT '' COMMENT '商品类目',
  sku_class_name VARCHAR(255) NOT NULL DEFAULT '' COMMENT 'SKU规格名',
  supplier_price_cent INT NOT NULL DEFAULT 0 COMMENT '申报价格（分）',
  cost_price_cent INT NOT NULL DEFAULT 0 COMMENT '成本价格（分）',
  price_review_status INT NOT NULL DEFAULT 0 COMMENT '价格审核状态',
  is_verify_price TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否已校验价格',
  lack_quantity INT NOT NULL DEFAULT 0 COMMENT '缺货数量',
  in_cart_number_7d INT NOT NULL DEFAULT 0 COMMENT '近7日用户加购数量',
  in_cart_number_total INT NOT NULL DEFAULT 0 COMMENT '用户累计加购数量',
  subscribe_arrival_remind_count INT NOT NULL DEFAULT 0 COMMENT '订阅到货提醒数量',
  today_sale_volume INT NOT NULL DEFAULT 0 COMMENT '今日销量',
  last_seven_days_sale_volume INT NOT NULL DEFAULT 0 COMMENT '近7日销量',
  last_thirty_days_sale_volume INT NOT NULL DEFAULT 0 COMMENT '近30日销量',
  total_sale_volume INT NOT NULL DEFAULT 0 COMMENT '累计销量',
  warehouse_inventory_num INT NOT NULL DEFAULT 0 COMMENT '仓内可用库存',
  expected_occupied_inventory_num INT NOT NULL DEFAULT 0 COMMENT '仓内预占用库存',
  unavailable_warehouse_inventory_num INT NOT NULL DEFAULT 0 COMMENT '仓内暂不可用库存',
  wait_delivery_inventory_num INT NOT NULL DEFAULT 0 COMMENT '已发货库存',
  wait_receive_num INT NOT NULL DEFAULT 0 COMMENT '已创建备货单待发货库存',
  wait_approve_inventory_num INT NOT NULL DEFAULT 0 COMMENT '待审核备货库存',
  seller_warehouse_stock INT NOT NULL DEFAULT 0 COMMENT '卖家仓库存',
  advice_quantity INT NOT NULL DEFAULT 0 COMMENT '建议备货量',
  available_sale_days DECIMAL(10,2) NULL COMMENT '库存可售天数',
  warehouse_available_sale_days DECIMAL(10,2) NULL COMMENT '仓内库存可售天数',
  purchase_config VARCHAR(128) NOT NULL DEFAULT '' COMMENT '备货逻辑',
  target_produce_days DECIMAL(10,2) NULL COMMENT '建议目标库存天数',
  target_produce_num INT NULL COMMENT '建议目标库存',
  advice_produce_num INT NULL COMMENT '建议生产或采购量',
  show_stock_guide TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否展示备货引导',
  row_json LONGTEXT NOT NULL COMMENT '原始明细JSON',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (id),
  KEY idx_sales_overall_rows_batch_id (batch_id),
  KEY idx_sales_overall_rows_supplier_id (supplier_id),
  KEY idx_sales_overall_rows_product_skc_id (product_skc_id),
  KEY idx_sales_overall_rows_product_sku_id (product_sku_id),
  KEY idx_sales_overall_rows_sales_volume (last_thirty_days_sale_volume, last_seven_days_sale_volume),
  CONSTRAINT fk_sales_overall_rows_batch_id FOREIGN KEY (batch_id) REFERENCES sales_overall_batches(id)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='销售总览快照明细表';
